# Proto/location/location_metadata.py

# Inland state / UT / city dictionary for disambiguation & inland fast-path
INLAND_LOCATIONS = {
    # States
    "andhra pradesh": "Andhra Pradesh",
    "amaravati": "Amaravati",
    "arunachal pradesh": "Arunachal Pradesh",
    "arunachal": "Arunachal Pradesh",
    "itanagar": "Itanagar",
    "assam": "Assam",
    "dispur": "Dispur",
    "guwahati": "Guwahati",
    "bihar": "Bihar",
    "patna": "Patna",
    "chhattisgarh": "Chhattisgarh",
    "raipur": "Raipur",
    "panaji": "Panaji",
    "panjim": "Panaji",
    "gujarat": "Gujarat",
    "gandhinagar": "Gandhinagar",
    "haryana": "Haryana",
    "chandigarh": "Chandigarh",
    "himachal pradesh": "Himachal Pradesh",
    "himachal": "Himachal Pradesh",
    "shimla": "Shimla",
    "jharkhand": "Jharkhand",
    "jhar": "Jharkhand",
    "ranchi": "Ranchi",
    "karnataka": "Karnataka",
    "bengaluru": "Bengaluru",
    "bangalore": "Bengaluru",
    "kerala": "Kerala",
    "thiruvananthapuram": "Thiruvananthapuram",
    "trivandrum": "Thiruvananthapuram",
    "kochi": "Kochi",
    "madhya pradesh": "Madhya Pradesh",
    "bhopal": "Bhopal",
    "indore": "Indore",
    "maharashtra": "Maharashtra",
    "mumbai": "Mumbai",
    "bombay": "Mumbai",
    "pune": "Pune",
    "manipur": "Manipur",
    "imphal": "Imphal",
    "meghalaya": "Meghalaya",
    "shillong": "Shillong",
    "mizoram": "Mizoram",
    "aizawl": "Aizawl",
    "nagaland": "Nagaland",
    "kohima": "Kohima",
    "odisha": "Odisha",
    "orissa": "Odisha",
    "bhubaneswar": "Bhubaneswar",
    "punjab": "Punjab",
    "rajasthan": "Rajasthan",
    "jaipur": "Jaipur",
    "sikkim": "Sikkim",
    "gangtok": "Gangtok",
    "tamil nadu": "Tamil Nadu",
    "tamilnadu": "Tamil Nadu",
    "chennai": "Chennai",
    "madras": "Chennai",
    "telangana": "Telangana",
    "hyderabad": "Hyderabad",
    "tripura": "Tripura",
    "agartala": "Agartala",
    "uttar pradesh": "Uttar Pradesh",
    "lucknow": "Lucknow",
    "uttarakhand": "Uttarakhand",
    "uttaranchal": "Uttarakhand",
    "dehradun": "Dehradun",
    "gairsain": "Gairsain",
    "west bengal": "West Bengal",
    "bengal": "West Bengal",
    "kolkata": "Kolkata",
    "calcutta": "Kolkata",

    # Union Territories & Capitals
    "andaman and nicobar islands": "Andaman and Nicobar Islands",
    "andaman": "Andaman and Nicobar Islands",
    "nicobar": "Andaman and Nicobar Islands",
    "andaman nicobar": "Andaman and Nicobar Islands",
    "port blair": "Port Blair",
    "dadra and nagar haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "dadra nagar haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "daman": "Dadra and Nagar Haveli and Daman and Diu",
    "dnhdd": "Dadra and Nagar Haveli and Daman and Diu",
    "silvassa": "Dadra and Nagar Haveli and Daman and Diu",
    "delhi": "Delhi",
    "new delhi": "Delhi",
    "national capital territory": "Delhi",
    "jammu and kashmir": "Jammu and Kashmir",
    "jammu kashmir": "Jammu and Kashmir",
    "jammu": "Jammu and Kashmir",
    "srinagar": "Srinagar",
    "ladakh": "Ladakh",
    "kargil": "Kargil",
    "lakshadweep": "Lakshadweep",
    "kavaratti": "Kavaratti",
    "puducherry": "Puducherry",
    "pondicherry": "Puducherry",
}

# Detailed location metadata classifying coastal access and region type
LOCATION_METADATA = {
    # Non-coastal States / Cities
    "madhya pradesh": {"name": "Madhya Pradesh", "type": "state", "coastal_access": False},
    "mp": {"name": "Madhya Pradesh", "type": "state", "coastal_access": False},
    "bhopal": {"name": "Bhopal", "type": "inland_city", "region": "Madhya Pradesh", "coastal_access": False},
    "indore": {"name": "Indore", "type": "inland_city", "region": "Madhya Pradesh", "coastal_access": False},
    "delhi": {"name": "Delhi", "type": "union_territory", "coastal_access": False},
    "new delhi": {"name": "Delhi", "type": "union_territory", "coastal_access": False},
    "rajasthan": {"name": "Rajasthan", "type": "state", "coastal_access": False},
    "jaipur": {"name": "Jaipur", "type": "inland_city", "region": "Rajasthan", "coastal_access": False},
    "punjab": {"name": "Punjab", "type": "state", "coastal_access": False},
    "haryana": {"name": "Haryana", "type": "state", "coastal_access": False},
    "uttar pradesh": {"name": "Uttar Pradesh", "type": "state", "coastal_access": False},
    "up": {"name": "Uttar Pradesh", "type": "state", "coastal_access": False},
    "lucknow": {"name": "Lucknow", "type": "inland_city", "region": "Uttar Pradesh", "coastal_access": False},
    "bihar": {"name": "Bihar", "type": "state", "coastal_access": False},
    "patna": {"name": "Patna", "type": "inland_city", "region": "Bihar", "coastal_access": False},
    "jharkhand": {"name": "Jharkhand", "type": "state", "coastal_access": False},
    "ranchi": {"name": "Ranchi", "type": "inland_city", "region": "Jharkhand", "coastal_access": False},
    "chhattisgarh": {"name": "Chhattisgarh", "type": "state", "coastal_access": False},
    "raipur": {"name": "Raipur", "type": "inland_city", "region": "Chhattisgarh", "coastal_access": False},
    "telangana": {"name": "Telangana", "type": "state", "coastal_access": False},
    "hyderabad": {"name": "Hyderabad", "type": "inland_city", "region": "Telangana", "coastal_access": False},
    "uttarakhand": {"name": "Uttarakhand", "type": "state", "coastal_access": False},
    "uk": {"name": "Uttarakhand", "type": "state", "coastal_access": False},

    # Coastal States / Reference Origin Cities
    "kolkata": {"name": "Kolkata", "type": "reference_city", "region": "West Bengal", "coastal_access": False},
    "calcutta": {"name": "Kolkata", "type": "reference_city", "region": "West Bengal", "coastal_access": False},
    "bengaluru": {"name": "Bengaluru", "type": "inland_city", "region": "Karnataka", "coastal_access": False},
    "bangalore": {"name": "Bengaluru", "type": "inland_city", "region": "Karnataka", "coastal_access": False},
    "pune": {"name": "Pune", "type": "inland_city", "region": "Maharashtra", "coastal_access": False},

    # Coastal Ports / Towns
    "digha": {"name": "Digha", "type": "coastal_town", "region": "West Bengal", "coastal_access": True},
    "mangalore": {"name": "Mangalore", "type": "fishing_port", "region": "Karnataka", "coastal_access": True},
    "kochi": {"name": "Kochi", "type": "fishing_port", "region": "Kerala", "coastal_access": True},
    "mumbai": {"name": "Mumbai", "type": "coastal_city", "region": "Maharashtra", "coastal_access": True},
    "chennai": {"name": "Chennai", "type": "coastal_city", "region": "Tamil Nadu", "coastal_access": True},
    "vizag": {"name": "Vizag", "type": "fishing_port", "region": "Andhra Pradesh", "coastal_access": True},
    "nellore": {"name": "Nellore", "type": "coastal_city", "region": "Andhra Pradesh", "coastal_access": True},
    "paradeep": {"name": "Paradeep", "type": "fishing_port", "region": "Odisha", "coastal_access": True},
    "veraval": {"name": "Veraval", "type": "fishing_port", "region": "Gujarat", "coastal_access": True},

    # Marine Regions
    "bay of bengal": {"name": "Bay of Bengal", "type": "marine_region", "coastal_access": True},
    "arabian sea": {"name": "Arabian Sea", "type": "marine_region", "coastal_access": True},
    "indian ocean": {"name": "Indian Ocean", "type": "marine_region", "coastal_access": True},

    # Inland States
    "madhya pradesh": {"name": "Madhya Pradesh", "type": "inland_state", "region": "Madhya Pradesh", "coastal_access": False},
    "madhya_pradesh": {"name": "Madhya Pradesh", "type": "inland_state", "region": "Madhya Pradesh", "coastal_access": False},
    "mp": {"name": "Madhya Pradesh", "type": "inland_state", "region": "Madhya Pradesh", "coastal_access": False},
}
